### ISSUE TITLE
Are there any plans to release missing files?

### ISSUE THREAD

**Issue by miu200521358** [zju3dv/4K4D#10]
Thanks for the great work !

I see that the following two files have not been released yet, but is there any plan to release them in the future?

- [scripts/realtime4dv/extract_images.py](https://github.com/zju3dv/4K4D/blob/main/scripts/realtime4dv/extract_images.py)
- [scripts/realtime4dv/extract_masks.py](https://github.com/zju3dv/4K4D/blob/main/scripts/realtime4dv/extract_masks.py)

thanks a lot

**Comment by dendenxu** [comment]
Ah @miu200521358, sorry for the confusion. I misplaced these files during release. They have been uploaded in the latest commit.

**Comment by miu200521358** [comment]
Thank you very much!
I have confirmed that two files have been added.
I am very excited to be able to move them now.
Thank you so much for your great research!
