### ISSUE TITLE
About real-time rendering

### ISSUE THREAD

**Issue by rypan1998** [zju3dv/4K4D#12]
Great work!
I wonder whether 4k4d can achieve real-time effect like the demo in [GPS Gaussian](https://github.com/ShunyuanZheng/GPS-Gaussian) ? If possible, can our algorithm still achieve such amazing framerates and rendering effect?

**Comment by dendenxu** [comment]
Hi @rypan1998! Excellent question! We developed 4K4D as a per-scene optimization algorithm. Predicting a persistent representation like 4K4D is actually one of our on-going research project!
