### ISSUE TITLE
How to convert CamPose.inf to extri.yml?

### ISSUE THREAD

**Issue by GuaGod** [zju3dv/4K4D#15]

**Comment by dendenxu** [comment]
Hi @GuaGod ! Thanks for using our code.
I assume you've downloaded the original NHR dataset. Right now we don't have a preprocessing script for the original NHR dataset, but I assume we can put one up quite easily. We will add a preprocessing script in the `scripts/preprocess` folder shortly.
In the meantime, you could try downloading [our processed NHR dataset](https://github.com/zju3dv/4K4D?tab=readme-ov-file#dna-rendering-nhr-and-zju-mocap-datasets) (which requires you to send an email to me).
