### ISSUE TITLE
About the release time of the code

### ISSUE THREAD

**Issue by yec22** [zju3dv/4K4D#3]
Hi, thanks for the great job !!!

I'm quite curious about the exact release time of your source code. 
Will you release the code in next month (November)? I can't wait to try it!

Looking forward to your reply !

**Comment by cchance27** [comment]
Same interested to see how hard it is to setup a test bench if it

**Comment by dendenxu** [comment]
Hi! Sorry for the late reply. 
We're planning on releasing before December, but unfortunately I cannot give a guarantee or an exact estimation. 
To tease a bit, 4K4D was developed using one of our internal volumetric video research codebase, which probably will be released at the same time with 4K4D! We're currently still cleaning up and adding documents to the codebase.

**Comment by dendenxu** [comment]
@cchance27 Personally I run my GUI tests on my Windows work PC (i7-11700, 56GB, 3060). Setting up an environment for 4K4D to render in the GUI on Windows was quite straight forward. All trainings are done on Linux servers and Linux GUI is also tested. I didn't bother with training on Windows but we do plan on testing it later.

**Comment by JunyuanDeng** [comment]
> Hi! Sorry for the late reply. We're planning on releasing before December, but unfortunately I cannot give a guarantee or an exact estimation. To tease a bit, 4K4D was developed using one of our internal volumetric video research codebase, which probably will be released at the same time with 4K4D! We're currently still cleaning up and adding documents to the codebase.

Any new updates?
