### ISSUE TITLE
How long does it take to train a model

### ISSUE THREAD

**Issue by Shell-bic** [zju3dv/4K4D#4]
How long does it take to extract the model? and how long does it take to generate a new action?
thanks a lot

**Comment by dendenxu** [comment]
Hi, as stated in the paper, a typical 200 frame sequence takes 800K iterations to converge. This process takes roughly 24 hours.
I'm not quite sure of what process you're refering to by "generate a new action", do you mind elaborating more?

**Comment by T-Ev** [comment]
So this translates to roughly 7.2 minutes per frame?

**Comment by JokerYan** [comment]
In the paper, it says an instant NGP is trained to initialize the point cloud. If I understand correctly, the point cloud does not move with time. So is one iNGP model trained for each frame?
Does the training time include the instant NGP training time?

**Comment by dendenxu** [comment]
@JokerYan Hi, iNGP is only used for initializing the static background point cloud for datasets with backgrounds (ENeRF-Outdoor and Mobile-Stage). This is done only once for the whole sequence and only takes a few minutes to complete.

**Comment by dendenxu** [comment]
@JokerYan That's correct. Compared to the actual training, space carving is almost instantaneous. In our implementation the space carving could sometimes even reach 3-5 FPS, roughly translating to 30s for a 150-frame sequence if we're only counting the actual computation.

**Comment by JokerYan** [comment]
Thank you. that is very helpful
