### ISSUE TITLE
Question about the pretrained models

### ISSUE THREAD

**Issue by brianneoberson** [zju3dv/4K4D#45]
Hello, 

I was wondering if the pretrained models were trained on the training views only or did you train on the whole dataset? (so including the 4 test views) 

Best regards

**Comment by dendenxu** [comment]
The released models are trained on full-resolution images of all views for the best visual quality for the release version of the code. 
For evaluation (matching the view selection and resolution selection used in the paper), please consider downloading the [reference images](https://drive.google.com/file/d/1xES9EoH7DwPaMcHbL8_g4HqCm7S1jIS2/view?usp=sharing). Note that images for the paper are produced using the training views only.

**Comment by brianneoberson** [comment]
Thank you for the quick answer! So if I understand correctly, the reference images used for evaluation were also used for training?
