### ISSUE TITLE
Image Resize

### ISSUE THREAD

**Issue by Yifever20002** [zju3dv/4K4D#53]
Thank you for such a great work! I'm trying to downsample the image for fitting CUDA consumption, do you have such an option like --downsampling_rate?

**Comment by Yifever20002** [comment]
Sorry for the inconvenience, I have found the "ratio" in dataset_cfg，and it works! But how can I get access to the cfg list to make sure what cfgs do you have?
![image](https://github.com/user-attachments/assets/d88d32d5-ce65-4f41-9a66-4a86ccdab006)

**Comment by dendenxu** [comment]
Hi, thanks for using our work!
As you've mentioned, we can programmatically resize the input images using the `ratio` entry.
As for the full list of config used: after running a evc command for example some `evc-train` command, you'll see a log directory created in `data/record/{exp_name}` (substitute your experiment name here), which will contain a yaml file named as `{exp_name}.yaml`. This is the full list of config inherited from all of your used config file (through the config inheritance system) and also the command line.

**Comment by Yifever20002** [comment]
> Hi, thanks for using our work! As you've mentioned, we can programmatically resize the input images using the `ratio` entry. As for the full list of config used: after running a evc command for example some `evc-train` command, you'll see a log directory created in `data/record/{exp_name}` (substitute your experiment name here), which will contain a yaml file named as `{exp_name}.yaml`. This is the full list of config inherited from all of your used config file (through the config inheritance system) and also the command line.

Thank you! I've found it.
