### ISSUE TITLE
easyvolcap.utils.console_utils -> inner: Runtime exception: 'SuperChargedR4DV is not in the samplers registry'

### ISSUE THREAD

**Issue by JunyuanDeng** [zju3dv/4K4D#7]
Hi, thanks for your great job!

I tried to visualize the result of NHR basketball dataset, but it came with the following error:

`easyvolcap.utils.console_utils -> inner: Runtime exception: 'SuperChargedR4DV is not in the samplers registry'`

Hope for your reply!

**Comment by dendenxu** [comment]
Hi! @JunyuanDeng Thanks for the interest. What command did you use for the visualization?
Moreover, the root cause for import errors in easyvolcap is almost always not the last error, could you please also paste the first error here? I'm suspecting some missing packages.

**Comment by JunyuanDeng** [comment]
![image](https://github.com/zju3dv/4K4D/assets/62542727/6e24c76e-dfe0-4392-854b-16f2c22fe1db)
![image](https://github.com/zju3dv/4K4D/assets/62542727/18434455-c286-4545-9306-59bbbd37ffb4)

**Comment by dendenxu** [comment]
Hi, I see that you previously installed EasyVolcap on your system. 4K4D is a fork and currently a superset of EasyVolcap, thus you need to replace the installation by running

```shell
# Run this inside the 4K4D repo
pip install -e . --no-build-isolation --no-deps
```

in the root of 4K4D.

I'll make the documentation clearer.

**Comment by JunyuanDeng** [comment]
Thanks for your prompt reply!

Now I have another problem:
![image](https://github.com/zju3dv/4K4D/assets/62542727/22582444-349e-4071-8c21-ce63e1dc4807)
![image](https://github.com/zju3dv/4K4D/assets/62542727/454cfaaa-65ff-4c6d-9d40-f4a913e9b93d)

**Comment by dendenxu** [comment]
Hi, glad to hear we've made progress.
What command did you use? And I might also need the directory content of `data/trained_model`.

**Comment by JunyuanDeng** [comment]
Oh, yes! After I put the pre-trained model in the wrong directory. Now it works!

The visualized result seems a little bit weird. Is it normal to see like this?
![image](https://github.com/zju3dv/4K4D/assets/62542727/e588de5a-c39a-422c-ad57-36fcb1e181f1)

**Comment by dendenxu** [comment]
Hi @JunyuanDeng this doesn't look right. I believe this is not the first frame of the basketball dataset. Could you please provide the command you used for this visualization? I rerun my tests with:

```shell
evc -t gui -c configs/projects/realtime4dv/rendering/4k4d_basketball.yaml,configs/specs/vf0.yaml
```

And the results look fine:

![image](https://github.com/zju3dv/4K4D/assets/43734697/356dd112-9770-480d-a2b0-e1dc728bf851)


On another note, maybe we should open a new issue regarding this.

**Comment by JunyuanDeng** [comment]
OK, thanks for your kind reply!
